name: Example Workflow on Ansible

on: workflow_dispatch

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run hostname
        run: |
           hostname=$(hostname)
           echo $hostname

        
      - name: Add SSH key to runner
        uses: webfactory/ssh-agent@v0.5.0    
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt install -y ansible

      - name: Run Ansible playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
        run: |
           ansible-playbook -i inventory playbook_test.yml
