name: Example Workflow on Ansible

on: workflow_dispatch

jobs:
  example_job:
  #  strategy:
  #    matrix:
  #      os: [ubuntu, centos]
  #      version: [18.04, 20.04, 7, 8]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run hostname
        run: |
           hostname=$(hostname)
           echo $hostname

        
      - name: Add SSH key to runner
        uses: webfactory/ssh-agent@v0.5.0    
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    #  - run: |
    #      ssh-add - <echo "${{ secrets.SSH_PRIVATE_KEY }}"
    #      ssh-keyscan -t rsa ${{ matrix.os }}-runner-${{ matrix.version }}.github.com >> ~/.ssh/known_hosts
  

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt install -y ansible

      - name: Run Ansible playbook
        #env:
          #ANSIBLE_HOST_KEY_CHECKING: false
        run: |
           HOSTNAME=$(hostname)
           ansible-playbook -i inventory.yml playbook_test.yml --extra-vars hostname=$HOSTNAME
