name: Parallel Workflows with Restart

on: 
  workflow_dispatch:

jobs:
  workflow-A:
    uses: ./.github/workflows/workflow-A.yaml
  workflow-B:
    uses: ./.github/workflows/workflow-B.yaml
  workflow-C:
    uses: ./.github/workflows/workflow-C.yaml
  Error_Check:
    needs: [workflow-A,workflow-B,workflow-C]
    runs-on: ubuntu-latest
    if: (needs.workflow-A.result == 'failure' || needs.workflow-B.result == 'failure' || needs.workflow-C.result == 'failure') && ${{ always() }}
    steps:
      - run: echo "There is a failure on one of the workflow"
