name: Parallel Workflows with Restart

on: 
  workflow_dispatch:

jobs:
  workflow-A:
    uses: ./.github/workflows/workflow-A.yaml
  workflow-B:
    uses: ./.github/workflows/workflow-B.yaml
  workflow-C:
    uses: ./.github/workflows/workflow-C.yaml
  restart-job:
    runs-on: ubuntu-latest
    needs: workflow-C
    if: ${{ failure() }}
    steps:
      - name: Get failed job ID
        id: get_job_id
        run: echo "::set-output name=job_id::${{ workflow-C.id }}"
      - name: Re-run failed job
        run: gh workflow run ${{ github.workflow }} -i job_id=${{ steps.get_job_id.outputs.job_id }}
