name: Parallel Workflows with Restart

on: 
  workflow_dispatch:

jobs:
  workflow-A:
    uses: ./.github/workflows/workflow-A.yaml
  workflow-B:
    uses: ./.github/workflows/workflow-B.yaml
  workflow-C:
    uses: ./.github/workflows/workflow-C.yaml
  restart-job:
    runs-on: ubuntu-latest
    needs: workflow-C
    if: ${{ always() && contains(needs.workflow-C.result, 'failure') }}   
    steps:
      - name: Login to GitHub CLI
        run: gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}
      - name: Set GH_TOKEN environment variable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "GH_TOKEN=$GH_TOKEN"
      - name: Re-run failed job
        run: |
          git clone https://github.com/ArkoProvo531/upload-artifact.git
          ls -lrt
          gh workflow run /.github/workflows/workflow-C.yaml --ref main
