name: Parallel Workflows with Restart

on: 
  workflow_dispatch:

jobs:
  workflow-A:
    uses: ./.github/workflows/workflow-A.yaml
  workflow-B:
    uses: ./.github/workflows/workflow-B.yaml
  workflow-C:
    uses: ./.github/workflows/workflow-C.yaml
  restart-job_A:
    runs-on: ubuntu-latest
    needs: workflow-A
    if: ${{ always() && contains(needs.workflow-A.result, 'failure') }}   
    steps:
      - name: Login to GitHub CLI
        run: gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}
      - name: Set GH_TOKEN environment variable
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: echo "GH_TOKEN=$GH_TOKEN"
      - name: Re-run failed job
        run: |
          gh repo clone ArkoProvo531/upload-artifact
          cd upload-artifact
          sudo chmod -R 755 /.github
          cd .github/workflows
          ls -a
          pwd
          gh workflow run workflow-A.yaml  
  restart-job_C:
    runs-on: ubuntu-latest
    needs: workflow-C
    if: ${{ always() && contains(needs.workflow-C.result, 'failure') }}   
    steps:
      - name: Login to GitHub CLI and rerun the failed job
        run: |
          gh auth login
          gh workflow list
