name: Parallel Workflows with Restart

on: 
  workflow_dispatch:

jobs:
  workflow-A:
    uses: ./.github/workflows/workflow-A.yaml
  workflow-B:
    uses: ./.github/workflows/workflow-B.yaml
  workflow-C:
    uses: ./.github/workflows/workflow-c.yaml
