name: Parallel Workflows with Restart

on: workflow_dispatch

jobs:
  parallel-workflows:
    permissions: write-all
    name: print-token
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workflow: [workflow-A, workflow-B, workflow-C]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run workflow
        uses: benc-uk/workflow-dispatch@v1.2.2
        continue-on-error: true
        with:
          ref: ${{ github.ref }}
          token: ${{ github.token }}
          workflow: ${{ matrix.workflow }}.yaml

      - name: Check for failures
        if: ${{ failure() }}
        run: |
          echo "One of the workflows failed. Restarting all workflows."
          exit 1
