name: Parallel Workflows with Restart

on: 
  workflow_dispatch:

jobs:
  workflow-A:
    uses: ./.github/workflows/workflow-A.yaml
  workflow-B:
    uses: ./.github/workflows/workflow-B.yaml
  workflow-C:
    uses: ./.github/workflows/workflow-C.yaml
  restart-job_A:
    needs: workflow-A
    if: ${{ always() && contains(needs.workflow-A.result, 'failure') }}   
    uses: ./.github/workflows/workflow-A.yaml 
  restart-job_B:
    needs: workflow-B
    if: ${{ always() && contains(needs.workflow-B.result, 'failure') }}   
    uses: ./.github/workflows/workflow-B.yaml   
  restart-job_C:
    #runs-on: ubuntu-latest
    needs: workflow-C
    if: ${{ always() && contains(needs.workflow-C.result, 'failure') }}   
    uses: ./.github/workflows/workflow-C.yaml
