name: Parallel Workflows with Restart

on: workflow_dispatch

jobs:
  parallel-workflows:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workflow: [workflow-A, workflow-B, workflow-C]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run workflow
        uses: benc-uk/workflow-dispatch@v1.2.2
        continue-on-error: true
        with:
          ref: ${{ github.ref }}
          token: ${{ github.token }}
          workflow: ${{ matrix.workflow }}.yaml
          
      - name: Failed statement
        if: failure() && github.workflow == ${{ matrix.workflow }}.yaml && github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
        run: |
          echo "One of the workflow is failed"    
          
  restart_when_failed:
    name: Restarts the scheduled run when it failed
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && failure()
    needs: [parallel-workflows]
    steps:
      - name: Retry the workflow
        run: |
          curl -i \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/ArkoProvo531/upload-artifact/actions/workflows/upload_download_arti.yaml/dispatches \
          -d '{"ref": "${{ github.ref }}" }'           

   #   - name: Check for failures
   #     if: ${{ failure() }}
   ##     run: |
    #      echo "One of the workflows failed. Restarting all workflows."
    #      exit 1
