name: Parallel Workflows with Restart

on: 
  workflow_dispatch:

jobs:
  workflow-A:
    uses: ./.github/workflows/workflow-A.yaml
  workflow-B:
    uses: ./.github/workflows/workflow-B.yaml
  workflow-C:
    uses: ./.github/workflows/workflow-C.yaml
  Error_Check:
    needs: [workflow-A,workflow-B,workflow-C]
    runs-on: ubuntu-latest
    if: ${{ always() && contains(needs.workflow-C.result, 'failure') }}
    steps:
      - name: Get failed job ID and rerun the failed job
        run: |
           echo "Failed job ID is ${{ needs.workflow-C.id }}"
           gh run rerun --job ${{ needs.workflow-C.id }}
