name: Node upload test

on:
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm test
          
      - name: Tar files
        run: tar -cvf my_file.tar dist  
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: my_file.tar  
            
      - name: To check the path
        shell: sh
        run: |
          pwd
          ls -lrt
          ls -la
          
      - uses: jfrog/setup-jfrog-cli@v1
      - name: Jfrog version
        run: jfrog --version
        
      - name: Download dist result
        uses: actions/download-artifact@v3
        with:
          name: dist-without-markdown  
          
      - name: To check the path
        shell: sh
        run: |
          pwd
          ls -lrt
          ls -la
    
      - name: Push artifact to Artifactory
        env:
          ARTIFACTORY_URL: https://arkoartifact.jfrog.io/artifactory
          ARTIFACTORY_USERNAME: ${{ secrets.JF_USER }}
          ARTIFACTORY_PASSWORD: ${{ secrets.JF_PASSWORD }}
          ARTIFACTORY_REPO: test1
        run: |
          jfrog rt u dist/* "${{ env.ARTIFACTORY_REPO }}" --url="${{ env.ARTIFACTORY_URL }}" --user="${{ env.ARTIFACTORY_USERNAME }}" --password="${{ env.ARTIFACTORY_PASSWORD }}"    
