name: Node upload and download test

on: 
  workflow_dispatch:
    inputs:
      input1:
        description: 'Input 1'
        required: true
      input2:
        description: 'Input 2'
        required: false
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: My Step
        run: echo "Input 1: ${{ github.event.inputs.input1 }}, Input 2: ${{ github.event.inputs.input2 }}"

  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Fetch workflow ID
        run: |
          echo ${{ github. run_id }}
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm test
          
      - name: Tar files
        run: tar -cvf my_file.tar dist  
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my_file
          path: my_file.tar
          
      - uses: jfrog/setup-jfrog-cli@v1
      - name: Jfrog version
        run: jfrog --version
        
      - name: Download dist result
        uses: actions/download-artifact@v3
        with:
          name: my_file 
    
      - name: Push artifact to Artifactory
        env:
          ARTIFACTORY_URL: https://arkoartifact.jfrog.io/artifactory
          ARTIFACTORY_USERNAME: ${{ secrets.JF_USER }}
          ARTIFACTORY_PASSWORD: ${{ secrets.JF_PASSWORD }}
          ARTIFACTORY_REPO: test1
        run: |
          jfrog rt u *.tar "${{ env.ARTIFACTORY_REPO }}" --url="${{ env.ARTIFACTORY_URL }}" --user="${{ env.ARTIFACTORY_USERNAME }}" --password="${{ env.ARTIFACTORY_PASSWORD }}"    
     
  download_artifact_from_jfrog:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: jfrog/setup-jfrog-cli@v1
      - name: Jfrog version
        run: jfrog --version
        
      - name: download artifact to local from jfrog
        shell: sh
        env:
          ARTIFACTORY_URL: https://arkoartifact.jfrog.io/artifactory
          ARTIFACTORY_USERNAME: ${{ secrets.JF_USER }}
          ARTIFACTORY_PASSWORD: ${{ secrets.JF_PASSWORD }}
          ARTIFACTORY_REPO: test1
        run: |
          mkdir new_download
          chmod 777 new_download
          jfrog rt dl "${{ env.ARTIFACTORY_REPO }}/*.tar" new_download/ --url="${{ env.ARTIFACTORY_URL }}" --user="${{ env.ARTIFACTORY_USERNAME }}" --password="${{ env.ARTIFACTORY_PASSWORD }}"    
          cd new_download
          ls -lrt
