name: workflow B

on: workflow_dispatch

jobs:
  workflow-B-Run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run workflow statement
        run: |
          echo "This is an example of workflow B "
          
