name: resusable-workflow-caller

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-workflow-A:
    uses: ArkoProvo531/upload-artifact/.github/workflows/workflow_called_A.yaml@main
    with:
      username: Within same repo

  call-workflow-B:
    uses: ArkoProvo531/Windows_msbuild_test/.github/workflows/workflow_called_B.yaml@master
    with:
      username: Outside Repo
